[book]
title = "Pharos RS"
authors = ["Pharos maintainers"]
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/lisboaigor/pharos-rs"
site-url = "/pharos-rs/"
