-- Pharos PostgreSQL migrations: monotonic ordering sequence for pharos_outbox
--
-- Pairs with the `seq` column in crates/pharos-postgres/src/eventing.rs's
-- schema constant. `pending`/`failed` now order by `seq`, an `IDENTITY`
-- column the database assigns at insert time, instead of `created_at` — a
-- producer's own wall clock, which two producers with skewed clocks (or
-- writing in the same instant) have no guarantee of agreeing on.

ALTER TABLE pharos_outbox
    ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_pharos_outbox_pending_seq
    ON pharos_outbox (seq)
    WHERE status = 'pending';

-- Superseded by idx_pharos_outbox_pending_seq now that `pending`/`failed`
-- order by `seq` instead of `created_at`.
DROP INDEX IF EXISTS idx_pharos_outbox_pending_created_at;
