use chrono::{DateTime, Utc};
use pharos_macros::DomainEvent;
use uuid::Uuid;

/// Events raised by the `Order` aggregate. `event_type`, `occurred_at`, and
/// `aggregate_id` are generated by `#[derive(DomainEvent)]` from field annotations.
///
/// The `#[aggregate_id]` field is a `String` so `DomainEvent::aggregate_id`
/// returns a borrow without allocating on every call.
#[derive(Debug, Clone, DomainEvent)]
pub enum OrderEvent {
    OrderCreated {
        #[aggregate_id]
        order_id: String,
        customer_id: Uuid,
        #[occurred_at]
        occurred_at: DateTime<Utc>,
    },
    ItemAdded {
        #[aggregate_id]
        order_id: String,
        item_id: Uuid,
        description: String,
        quantity: u32,
        unit_price_cents: u64,
        #[occurred_at]
        occurred_at: DateTime<Utc>,
    },
    OrderConfirmed {
        #[aggregate_id]
        order_id: String,
        total_cents: u64,
        #[occurred_at]
        occurred_at: DateTime<Utc>,
    },
    OrderCancelled {
        #[aggregate_id]
        order_id: String,
        reason: String,
        #[occurred_at]
        occurred_at: DateTime<Utc>,
    },
}
