use pharos_core::{DomainError, DomainResult, ValueObject};
use pharos_macros::id_type;

// Domain identifiers — UUID newtypes generated by the macro.
id_type!(OrderId, CustomerId, ItemId);

// ── Money ────────────────────────────────────────────────────────────────────

/// Monetary amount stored in cents (no floating point in internal state).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Money {
    cents: u64,
    currency: &'static str,
}

impl ValueObject for Money {}

impl Money {
    /// Builds a BRL amount from reais, rounding to the nearest cent.
    pub fn brl(reais: f64) -> DomainResult<Self> {
        if reais < 0.0 || !reais.is_finite() {
            return Err(DomainError::Validation("invalid monetary amount".into()));
        }
        Ok(Self {
            cents: (reais * 100.0).round() as u64,
            currency: "BRL",
        })
    }

    pub fn from_cents(cents: u64) -> Self {
        Self {
            cents,
            currency: "BRL",
        }
    }

    pub fn zero() -> Self {
        Self::from_cents(0)
    }

    pub fn cents(&self) -> u64 {
        self.cents
    }

    pub fn add(&self, other: &Self) -> DomainResult<Self> {
        if self.currency != other.currency {
            return Err(DomainError::BusinessRule("different currencies".into()));
        }
        Ok(Self {
            cents: self.cents + other.cents,
            currency: self.currency,
        })
    }

    /// Multiplies by a quantity using integer arithmetic with no precision loss.
    pub fn mul(&self, fator: u32) -> Self {
        Self {
            cents: self.cents * fator as u64,
            currency: self.currency,
        }
    }
}

impl std::fmt::Display for Money {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "R$ {}.{:02}", self.cents / 100, self.cents % 100)
    }
}

// ── Quantity ────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Quantity(u32);

impl ValueObject for Quantity {}

impl Quantity {
    pub fn new(v: u32) -> DomainResult<Self> {
        if v == 0 {
            return Err(DomainError::Validation("quantity must be > 0".into()));
        }
        Ok(Self(v))
    }

    pub fn value(&self) -> u32 {
        self.0
    }
}
